version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/health_monitor
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - IQAIR_API_KEY=${IQAIR_API_KEY}
      - NUTRITIONIX_APP_ID=${NUTRITIONIX_APP_ID}
      - NUTRITIONIX_API_KEY=${NUTRITIONIX_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=health_monitor
    ports:
      - "5432:5432"

volumes:
  postgres_data: 